# Generated by Django 3.1.5 on 2022-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
