# Generated by Django 3.1.5 on 2022-05-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('activity', '0002_auto_20220410_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='location.location'),
        ),
    ]
