# Generated by Django 3.1.5 on 2022-04-09 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
