# Generated by Django 3.1.5 on 2022-04-11 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=40)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('county', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='location.location')),
            ],
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country', 'state', 'county', 'city'], name='location_lo_country_0447ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('country', 'state', 'county', 'city')},
        ),
    ]
